# ~/.tmux.conf

# Clear all default bindings in the prefix table
unbind -a -T prefix

# Allow mouse controls
set -g mouse on

# Move between panes (leader + hjkl)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Create new pane in a direction (leader + Ctrl+hjkl)
bind C-h split-window -h -b
bind C-l split-window -h
bind C-k split-window -v -b
bind C-j split-window -v

# Resize pane (leader + Alt+hjkl)
bind M-h resize-pane -L 5
bind M-j resize-pane -D 5
bind M-k resize-pane -U 5
bind M-l resize-pane -R 5

# Window navigation (leader + Ctrl-m / Ctrl+n)
bind C-m next-window
bind C-n previous-window

# Jump to numbered window
bind 0 select-window -t 0
bind 1 select-window -t 1
bind 2 select-window -t 2
bind 3 select-window -t 3
bind 4 select-window -t 4
bind 5 select-window -t 5
bind 6 select-window -t 6
bind 7 select-window -t 7
bind 8 select-window -t 8
bind 9 select-window -t 9

# Detach
bind d detach-client

# Help
bind ? list-keys

# Pickers / switchers
bind w choose-tree -w
bind s choose-tree -s

# Rename
bind , command-prompt -I "#W" "rename-window '%%'"
bind $ command-prompt -I "#S" "rename-session '%%'"

# Break pane into new window
bind ! break-pane

# Clock
bind t clock-mode

# Show messages
bind '~' show-messages

# Misc
bind : command-prompt
bind { copy-mode
bind ] paste-buffer
bind x comfirm-before -p "kill pane? (y/n)" kill-pane
bind z resize-pane -Z
bind c new-window
