@echo off

:::: Portable Environment Variables
set MS_PORTABLE_ENVIRONMENT_ROOT=C:\Environment

:::: 7-zip
set MS_7ZIP_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\7-zip
set MS_7ZIP_VERSION=26.0
set MS_7ZIP_PATH=%MS_7ZIP_ROOT%\%MS_7ZIP_VERSION%
set PATH=%MS_7ZIP_PATH%;%PATH%

:::: BalenaEtcher
set MS_BALENA_ETCHER_PATH=%MS_PORTABLE_ENVIRONMENT_ROOT%\BalenaEtcher
set PATH=%MS_BALENA_ETCHER_PATH%;%PATH%

:::: Blender
set MS_BLENDER_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Blender
set MS_BLENDER_VERSION=5.1
set MS_BLENDER_PATH=%MS_BLENDER_ROOT%\%MS_BLENDER_VERSION%
set PATH=%MS_BLENDER_PATH%;%PATH%

:::: cmake
set MS_CMAKE_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\cmake
set MS_CMAKE_VERSION=4.3.1
set MS_CMAKE_PATH=%MS_CMAKE_ROOT%\%MS_CMAKE_VERSION%
set PATH=%MS_CMAKE_PATH%\bin;%PATH%

:::: composer
set MS_COMPOSER_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\composer
set MS_COMPOSER_VERSION=2.9.5
set MS_COMPOSER_PATH=%MS_COMPOSER_ROOT%\%MS_COMPOSER_VERSION%
set PATH=%MS_COMPOSER_PATH%;%PATH%

:::: CPU-Z
set MS_CPUZ_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\CPU-Z
set MS_CPUZ_VERSION=2.19.0
set MS_CPUZ_PATH=%MS_CPUZ_ROOT%\%MS_CPUZ_VERSION%
set PATH=%MS_CPUZ_PATH%;%PATH%

:::: CrystalDiskInfo
set MS_CRYSTAL_DISK_INFO_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\CrystalDiskInfo
set MS_CRYSTAL_DISK_INFO_VERSION=9.8.0
set MS_CRYSTAL_DISK_INFO_PATH=%MS_CRYSTAL_DISK_INFO_ROOT%\%MS_CRYSTAL_DISK_INFO_VERSION%
set PATH=%MS_CRYSTAL_DISK_INFO_PATH%;%PATH%

:::: CrystalDiskMark
set MS_CRYSTAL_DISK_MARK_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\CrystalDiskMark
set MS_CRYSTAL_DISK_MARK_VERSION=9.0.2
set MS_CRYSTAL_DISK_MARK_PATH=%MS_CRYSTAL_DISK_MARK_ROOT%\%MS_CRYSTAL_DISK_MARK_VERSION%
set PATH=%MS_CRYSTAL_DISK_MARK_PATH%;%PATH%

:::: Everything
set MS_EVERYTHING_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Everything
set MS_EVERYTHING_VERSION=1.4.1.1032
set MS_EVERYTHING_PATH=%MS_EVERYTHING_ROOT%\%MS_EVERYTHING_VERSION%
set PATH=%MS_EVERYTHING_PATH%;%PATH%

:::: fd
set MS_FD_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\fd
set MS_FD_VERSION=10.4.2
set MS_FD_PATH=%MS_FD_ROOT%\%MS_FD_VERSION%
set PATH=%MS_FD_PATH%;%PATH%

:::: FilePilot
set MS_FILE_PILOT_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\FilePilot
set MS_FILE_PILOT_VERSION=0.7.0
set MS_FILE_PILOT_PATH=%MS_FILE_PILOT_PATH%\%MS_FILE_PILOT_VERSION%
set PATH=%MS_FILE_PILOT_PATH%;%PATH%

:::: Flowlauncher
set MS_FLOWLAUNCHER_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\FlowLauncher
set MS_FLOWLAUNCHER_VERSION=2.1.1
set MS_FLOWLAUNCHER_PATH=%MS_FLOWLAUNCHER_ROOT%\%MS_FLOWLAUNCHER_VERSION%
set PATH=%MS_FLOWLAUNCHER_PATH%;%PATH%

:::: Git
set MS_GIT_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Git
set MS_GIT_VERSION=2.53.0.windows.2
set MS_GIT_PATH=%MS_GIT_ROOT%\%MS_GIT_VERSION%
set PATH=%MS_GIT_PATH%\bin;%PATH%

:::: go
set MS_GO_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\go
set MS_GO_VERSION=1.26.1
set MS_GO_PATH=%MS_GO_ROOT%\%MS_GO_VERSION%
:: Base dir
set GOROOT=%MS_GO_PATH%
:: workspace, module cache, installed bins
set GOPATH=%GOROOT%\gopath
:: puts installed tools next to go/gofmt
set GOBIN=%GOROOT%\bin
:: build cache
set GOCACHE=%GOROOT%\go-cache
set PATH=%GOBIN%;%PATH%

:::: GPU-Z
set MS_GPUZ_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\GPU-Z
set MS_GPUZ_VERSION=2.69.0
set MS_GPUZ_PATH=%MS_GPUZ_ROOT%\%MS_GPUZ_VERSION%
set PATH=%MS_GPUZ_PATH%;%PATH%

:::: gzip
set MS_GZIP_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\gzip
set MS_GZIP_VERSION=1.3.12
set MS_GZIP_PATH=%MS_GZIP_ROOT%\%MS_GZIP_VERSION%
set PATH=%MS_GZIP_PATH%\bin;%PATH%

:::: HardwareInfo
set MS_HARDWAREINFO_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\HardwareInfo
set MS_HARDWAREINFO_VERSION=8.44-5935
set MS_HARDWAREINFO_PATH=%MS_HARDWAREINFO_ROOT%\%MS_HARDWAREINFO_VERSION%
set PATH=%MS_HARDWAREINFO_PATH%;%PATH%

:::: HWMonitor
set MS_HWMONITOR_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\HWMonitor
set MS_HWMONITOR_VERSION=1.6.2.0
set MS_HWMONITOR_PATH=%MS_HWMONITOR_ROOT%\%MS_HWMONITOR_VERSION%
set PATH=%MS_HWMONITOR_PATH%;%PATH%

:::: ipscan
set MS_IPSCAN_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\ipscan
set MS_IPSCAN_VERSION=3.9.3
set MS_IPSCAN_PATH=%MS_IPSCAN_ROOT%\%MS_IPSCAN_VERSION%
set PATH=%MS_IPSCAN_PATH%;%PATH%

:::: jai
set MS_JAI_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\jai
set MS_JAI_VERSION=beta-0.2.028
set MS_JAI_PATH=%MS_JAI_ROOT%\%MS_JAI_VERSION%
set PATH=%MS_JAI_PATH%\bin;%PATH%

:::: jails (language server for jai)
set MS_JAILS_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\jails
set MS_JAILS_VERSION=0.2.1
set MS_JAILS_PATH=%MS_JAILS_ROOT%\%MS_JAILS_VERSION%
set PATH=%MS_JAILS_PATH%;%PATH%

:::: java
set MS_JAVA_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\java
set MS_JAVA_VERSION=adoptium\jdk_25.0.2_10
set MS_JAVA_PATH=%MS_JAVA_ROOT%\%MS_JAVA_VERSION%
set JAVA_HOME=%MS_JAVA_PATH%
set PATH=%MS_JAVA_PATH%\bin;%PATH%

:::: julia
set MS_JULIA_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\julia
set MS_JULIA_VERSION=1.12.5
set MS_JULIA_PATH=%MS_JULIA_ROOT%\%MS_JULIA_VERSION%
set PATH=%MS_JULIA_PATH%\bin;%PATH%

:::: llvm
set MS_LLVM_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\llvm
set MS_LLVM_VERSION=22.1.2
set MS_LLVM_PATH=%MS_LLVM_ROOT%\%MS_LLVM_VERSION%
set PATH=%MS_LLVM_PATH%\bin;%PATH%

:::: lua
set MS_LUA_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\lua
set MS_LUA_VERSION=5.1
set MS_LUA_PATH=%MS_LUA_ROOT%\%MS_LUA_VERSION%
set PATH=%MS_LUA_PATH%;%PATH%

:::: lua-language-server
set MS_LUA_LANGUAGE_SERVER_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\lua-language-server
set MS_LUA_LANGUAGE_SERVER_VERSION=3.18.2
set MS_LUA_LANGUAGE_SERVER_PATH=%MS_LUA_LANGUAGE_SERVER_ROOT%\%MS_LUA_LANGUAGE_SERVER_VERSION%
set PATH=%MS_LUA_LANGUAGE_SERVER_PATH%\bin;%PATH%

:::: luarocks
set MS_LUAROCKS_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\luarocks
set MS_LUAROCKS_VERSION=3.13.0
set MS_LUAROCKS_PATH=%MS_LUAROCKS_ROOT%\%MS_LUAROCKS_VERSION%
set PATH=%MS_LUAROCKS_PATH%;%PATH%

:::: msys64
set MS_MSYS64_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\msys64
set MS_MSYS64_PATH=%MS_MSYS64_ROOT%
set PATH=%MS_MSYS64_PATH%;%PATH%

:::: Neovim
set MS_NEOVIM_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\neovim
set MS_NEOVIM_VERSION=0.12.1
set MS_NEOVIM_PATH=%MS_NEOVIM_ROOT%\%MS_NEOVIM_VERSION%
set PATH=%MS_NEOVIM_PATH%\bin;%PATH%
:: XDG Homes (Currently just for neovim)
set XDG_CONFIG_HOME=C:\dev\my-tooling
set XDG_DATA_HOME=%MS_NEOVIM_PATH%\xdg_data_home
set XDG_STATE_HOME=%MS_NEOVIM_PATH%\xdg_state_home
set XDG_CACHE_HOME=%MS_NEOVIM_PATH%\xdg_cache_home

:::: Node/NPM
set MS_NODE_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Node
set MS_NODE_VERSION=25.9.0
set MS_NODE_PATH=%MS_NODE_ROOT%\%MS_NODE_VERSION%
set NPM_CONFIG_PREFIX=%MS_NODE_ROOT%\npm-global
set NPM_CONFIG_CACHE=%MS_NODE_ROOT%\.npm
set NPM_CONFIG_USERCONFIG=%MS_NODE_ROOT%\.npmrc
set PATH=%NPM_CONFIG_PREFIX%;%PATH%
set PATH=%MS_NODE_PATH%;%PATH%

:::: Notepad++
set MS_NOTEPADPLUSPLUS_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Notepad++
set MS_NOTEPADPLUSPLUS_VERSION=8.9.3
set MS_NOTEPADPLUSPLUS_PATH=%MS_NOTEPADPLUSPLUS_ROOT%\%MS_NOTEPADPLUSPLUS_VERSION%
set PATH=%MS_NOTEPADPLUSPLUS_PATH%;%PATH%

:::: PDFArranger
set MS_PDFARRANGER_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\PDFArranger
set MS_PDFARRANGER_VERSION=1.13
set MS_PDFARRANGER_PATH=%MS_PDFARRANGER_ROOT%\%MS_PDFARRANGER_VERSION%
set PATH=%MS_PDFARRANGER_PATH%;%PATH%

:::: Perl
set MS_PERL_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\perl
set MS_STRAWBERRY_PERL_VERSION=5.42.0.1
set MS_STRAWBERRY_PERL_PATH=%MS_PERL_ROOT%\strawberry\%MS_STRAWBERRY_PERL_VERSION%
call %MS_STRAWBERRY_PERL_PATH%\portableshell.bat /SETENV

:::: PHP
set MS_PHP_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\php
set MS_PHP_VERSION=8.5.4-x64-not-thread-safe
set MS_PHP_PATH=%MS_PHP_ROOT%\%MS_PHP_VERSION%
set PATH=%MS_PHP_PATH%;%PATH%

:::: Powershell
set MS_POWERSHELL_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Powershell
set MS_POWERSHELL_VERSION=7.6.0
set MS_POWERSHELL_PATH=%MS_POWERSHELL_ROOT%\%MS_POWERSHELL_VERSION%
set PATH=%MS_POWERSHELL_PATH%;%PATH%

:::: Python
set MS_PYTHON_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Python
set MS_WINPYTHON_VERSION=3.14.3.0dot
set MS_WINPYTHON_PATH=%MS_PYTHON_ROOT%\WinPython\%MS_WINPYTHON_VERSION%
call %MS_WINPYTHON_PATH%\Scripts\env.bat

:::: Ruby
set MS_RUBY_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Ruby
set MS_RUBY_VERSION=Ruby34-x64
set MS_RUBY_PATH=%MS_RUBY_ROOT%\%MS_RUBY_VERSION%
:: Where Ruby gems are installed to
set GEM_HOME=%MS_RUBY_PATH%\gems
:: List of directories that Ruby searches for installed gems
set GEM_PATH=%MS_RUBY_PATH%\gems;
:: Put both ruby and installed gems on path
set PATH=%MS_RUBY_PATH%\bin;%GEM_HOME%\bin;%PATH%

:::: Rufus
set MS_RUFUS_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Rufus
set MS_RUFUS_VERSION=4.13
set MS_RUFUS_PATH=%MS_RUFUS_ROOT%\%MS_RUFUS_VERSION%
set PATH=%MS_RUFUS_PATH%;%PATH%

:::: Rust Variables
set MS_RUST_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Rust
set CARGO_HOME=%MS_RUST_ROOT%\.cargo
set RUSTUP_HOME=%MS_RUST_ROOT%\.rustup
set PATH=%CARGO_HOME%\bin;%PATH%

:::: SourceGit
set MS_SOURCEGIT_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\SourceGit
set PATH=%MS_SOURCEGIT_ROOT%;%PATH%

:::: unzip
set MS_UNZIP_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\unzip
set MS_UNZIP_VERSION=5.51
set MS_UNZIP_PATH=%MS_UNZIP_ROOT%\%MS_UNZIP_VERSION%
set PATH=%MS_UNZIP_PATH%\bin;%PATH%

:::: VLC
set MS_VLC_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\vlc
set MS_VLC_VERSION=3.0.23
set MS_VLC_PATH=%MS_VLC_ROOT%\%MS_VLC_VERSION%
set PATH=%MS_VLC_PATH%;%PATH%

:::: VsCode
set MS_VSCODE_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\VsCode
set PATH=%MS_VSCODE_ROOT%;%PATH%

:::: VulkanSDK
set MS_VULKAN_SDK_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\VulkanSDK
set MS_VULKAN_SDK_VERSION=1.4.341.1
set MS_VULKAN_SDK_PATH=%MS_VULKAN_SDK_ROOT%\%MS_VULKAN_SDK_VERSION%
set VULKAN_SDK=%MS_VULKAN_SDK_PATH%
set VK_LAYER_PATH=%MS_VULKAN_SDK_PATH%\bin
set PATH=%MS_VULKAN_SDK_PATH%\bin;%PATH%

:::: wget
set MS_WGET_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\wget
set MS_WGET_VERSION=1.21.4
set MS_WGET_PATH=%MS_WGET_ROOT%\%MS_WGET_VERSION%
set PATH=%MS_WGET_PATH%;%PATH%

:::: Wireshark
set MS_WIRESHARKPORTABLE_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\WiresharkPortable64
set PATH=%MS_WIRESHARKPORTABLE_ROOT%;%PATH%

:::: WizTree
set MS_WIZTREE_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\WizTree
set MS_WIZTREE_VERSION=4.3.1
set MS_WIZTREE_PATH=%MS_WIZTREE_ROOT%\%MS_WIZTREE_VERSION%
set PATH=%MS_WIZTREE_PATH%;%PATH%

:::: Zig
set MS_ZIG_ROOT=%MS_PORTABLE_ENVIRONMENT_ROOT%\Zig
set MS_ZIG_VERSION=0.16.0
set MS_ZIG_PATH=%MS_ZIG_ROOT%\%MS_ZIG_VERSION%
set PATH=%MS_ZIG_PATH%;%PATH%

:: Visual Studio developer command prompt init
if exist "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat" (
    call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat"
) else (
    echo vcvars64.bat not found, skipping VS environment setup.
)
