# lib/build.sh — layered build engine behind setup.sh.
#
# A layer is a directory laid out like this repo; every part is optional. The
# stack is [this repo] [each --layer DIR, in order] [host layer], lowest
# precedence first. Each layer's layer.sh declares targets (link, link_each,
# block, generate, json, step); a target combines its path from EVERY layer,
# so a layer only adds files and never needs to know what the others contain.
# Targets run as they are declared. See docs/integration-guide.md.
#
# Must stay compatible with bash 3.2 (macOS /bin/bash): no associative arrays,
# no mapfile, no `readlink -f`, no ${var,,}.

STAMP="$(date +%Y%m%d%H%M%S)"
MODE=install
changes=0
problems=0
warnings=0
LAYERS=()       # absolute layer roots, lowest precedence first
LAYER=""        # root of the layer whose layer.sh is being sourced
SKIPS=()        # --skip patterns (destinations or step names)
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE_DIR="$CONFIG_HOME/dotfiles"
HOST_LAYER="${DOTFILES_HOST_LAYER:-$STATE_DIR/host}"
BUILD="$STATE_DIR/build"        # generated files and the record of what's managed
RECORD="$BUILD/managed"
GEN_MARK="dotfiles: generated by setup.sh; edit the layers and re-run setup, not this file"

build_usage() {
  cat <<EOF
Usage: $(basename "$0") [--layer DIR]... [--skip PATTERN]... [option]

Build this machine's configs from a stack of layers: this repo, then each
--layer DIR in the order given, then the host layer
($HOST_LAYER, if it exists). Later layers win. Each layer's
layer.sh declares targets; every target gathers its files from all layers.
See docs/integration-guide.md in $DOTFILES.

  (none)        Create or refresh everything. Files in the way are moved to
                <name>.backup.<timestamp>. Things managed by an earlier run
                that this stack no longer produces are removed. Safe to re-run.
  -n, --dry-run Print what would change without touching anything.
  -s, --status  Show the state of every target:
                  ok      up to date
                  absent  not set up yet
                  DIFF    exists but differs from what the layers produce
                  FILE    a real file is in the way (will be backed up)
                  OTHER   a symlink pointing somewhere else (will be replaced)
                  LEGACY  an old symlink into a layer (will be replaced)
                  stale   managed by an earlier run, not by this stack
                  todo    a setup step still needs to run
                  WARN    a later layer overrides an earlier layer's item
  -u, --uninstall
                Remove everything setup manages: links, generated files,
                managed blocks and the JSON keys it set. Host content outside
                the blocks, backups and what steps did are left in place.
  --layer DIR   Add a layer on top of the ones before it. Downstream repos
                pass themselves this way from their own setup.sh.
  --skip PATTERN
                Leave out targets whose destination or step name matches the
                shell pattern (e.g. "*/ghostty/*", "GNOME Terminal profile").
                "<layer name>:PATTERN" skips only that layer's targets, so a
                layer can replace a lower one's target at the same dest.
  -h, --help    Show this help.
EOF
}

# Print a status line; $HOME is shown as ~.
say() {
  local msg="$2" t='~'
  printf '  %-8s %s\n' "$1" "${msg//"$HOME"/$t}"
}
problem() { say "$1" "$2"; problems=$((problems + 1)); }
warn()    { say WARN "$1"; warnings=$((warnings + 1)); }
run()     { if [[ $MODE == dry-run ]]; then :; else "$@"; fi; }

# Single-quote a string for sh.
shq() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

# Display name of a layer root.
layer_name() {
  if [[ $1 == "$HOST_LAYER" ]]; then echo host; else basename "$1"; fi
}

# Layer roots joined with ':' (exported to shells as $DOTFILES_LAYERS).
layers_joined() {
  local IFS=:
  echo "${LAYERS[*]}"
}

# Print the target of a symlink (one level), or nothing.
link_target() { [[ -L $1 ]] && readlink "$1" || true; }

# Like link_target, but relative targets are made absolute.
abs_target() {
  local t
  t="$(link_target "$1")"
  case $t in
    ""|/*) echo "$t" ;;
    *)     echo "$(cd "$(dirname "$1")" && pwd -P)/$t" ;;
  esac
}

# True if PATH lies inside one of the layers.
in_layer() {
  local l
  [[ -n $1 ]] || return 1
  for l in "${LAYERS[@]}"; do
    case $1 in "$l"|"$l"/*) return 0 ;; esac
  done
  return 1
}

# Record a managed destination so a later run can prune it (kind: link, gen,
# block:<style>, json).
record() { printf '%s\t%s\n' "$1" "$2" >> "$TMPD/record"; }

# claim <dest> <signature>: returns 1 if the target should not run because
# it's skipped or was already declared identically (two layers may declare
# the same target). A different declaration for the same dest is a problem.
claim() {
  local dest="$1" sig="$2" prev p lname
  lname="$(layer_name "$LAYER")"
  for p in ${SKIPS[@]+"${SKIPS[@]}"}; do
    # A pattern prefixed "<layer name>:" only skips that layer's targets, so
    # a layer can replace a lower one's target at the same dest.
    case $p in "$lname:"*) p="${p#"$lname:"}" ;; esac
    # shellcheck disable=SC2254
    case $dest in $p) say skip "$dest"; return 1 ;; esac
    case ${dest#step: } in $p) say skip "$dest"; return 1 ;; esac
  done
  prev="$(awk -F'\t' -v d="$dest" '$1 == d { print $2; exit }' "$TMPD/claims")"
  if [[ -n $prev ]]; then
    [[ $prev == "$sig" ]] ||
      problem CONFLICT "$dest declared twice: '$prev' and '$sig' ($(layer_name "$LAYER"))"
    return 1
  fi
  printf '%s\t%s\n' "$dest" "$sig" >> "$TMPD/claims"
}

# free_parents <dest>: an ancestor of dest that is a symlink into a layer is
# an old whole-directory link (e.g. ~/.config/nvim -> repo/nvim); writing
# through it would write into the repo. Removes it (install/uninstall) or
# reports it. Sets GONE=1 when dest should be treated as not existing yet.
free_parents() {
  local d="${1%/*}" t
  GONE=0
  while [[ -n $d && $d != / ]]; do
    if [[ -L $d ]]; then
      t="$(abs_target "$d")"
      if in_layer "$t"; then
        if [[ $MODE == status || $MODE == dry-run ]]; then
          GONE=1
          # Report each old link once; dry-run and status don't remove it.
          grep -qxF -e "$d" "$TMPD/legacy" && return 0
          echo "$d" >> "$TMPD/legacy"
        fi
        case $MODE in
          status)    say LEGACY "$d -> $t (old directory link)" ;;
          dry-run)   say unlink "$d (old directory link -> $t)"; changes=$((changes + 1)) ;;
          install|uninstall)
            rm "$d"; say unlink "$d (old directory link -> $t)"; changes=$((changes + 1)) ;;
        esac
        return 0
      fi
    fi
    d="${d%/*}"
  done
}

# ensure_dir <dir>: dir must be a real directory (not a link) for per-item links.
ensure_dir() {
  local dir="$1" t
  free_parents "$dir/."
  [[ $GONE == 1 ]] && return 0
  if [[ -L $dir ]]; then
    t="$(abs_target "$dir")"
    case $MODE in
      status)    say OTHER "$dir -> $t (should be a real directory)" ;;
      uninstall) ;;
      *)
        say backup "$dir -> $dir.backup.$STAMP (directory link to $t)"
        run mv "$dir" "$dir.backup.$STAMP"
        changes=$((changes + 1))
        ;;
    esac
  fi
}

# place_link <src> <dest>: make dest a symlink to src.
place_link() {
  local src="$1" dest="$2" current=""
  free_parents "$dest"
  [[ $GONE == 1 ]] || current="$(link_target "$dest")"

  case $MODE in
    status)
      if [[ $GONE == 1 ]]; then say absent "$dest"
      elif [[ $current == "$src" ]]; then say ok "$dest"
      elif [[ -n $current ]] && in_layer "$current"; then say LEGACY "$dest -> $current"
      elif [[ -n $current ]]; then say OTHER "$dest -> $current"
      elif [[ -e $dest ]]; then say FILE "$dest (not linked)"
      else say absent "$dest"
      fi
      ;;

    uninstall)
      if [[ -n $current ]] && in_layer "$current"; then
        rm "$dest"; say removed "$dest"; changes=$((changes + 1))
      fi
      ;;

    install|dry-run)
      [[ $current == "$src" ]] && return 0
      if [[ -n $current ]]; then
        say relink "$dest (was -> $current)"
        run rm "$dest"
      elif [[ -e $dest && $GONE != 1 ]]; then
        say backup "$dest -> $dest.backup.$STAMP"
        run mv "$dest" "$dest.backup.$STAMP"
      fi
      run mkdir -p "$(dirname "$dest")"
      run ln -s "$src" "$dest"
      say link "$dest -> $src"
      changes=$((changes + 1))
      ;;
  esac
}

# put_file <dest> <new content file> <label>: write content to dest if it
# differs (install), keeping dest's mode when it is already a regular file.
# The caller has handled links and backups.
put_file() {
  local dest="$1" new="$2" label="$3"
  say "$label" "$dest"
  changes=$((changes + 1))
  [[ $MODE == install ]] || return 0
  if [[ -L $dest ]]; then rm "$dest"; fi
  mkdir -p "$(dirname "$dest")"
  if [[ -f $dest ]]; then cat "$new" > "$dest"; else cp "$new" "$dest"; fi
}

# ---------------------------------------------------------------- targets ---

# link <path> <dest>
# Symlink dest to <path> in the highest layer that has it. A later layer's
# file replaces an earlier one's whole (with a WARN).
link() {
  local sub="$1" dest="$2" l src=""
  claim "$dest" "link $sub" || return 0
  for l in "${LAYERS[@]}"; do
    [[ -e $l/$sub ]] || continue
    [[ -n $src ]] && warn "$dest: $(layer_name "$l") overrides $(layer_name "${src%/"$sub"}")"
    src="$l/$sub"
  done
  if [[ -z $src ]]; then
    problem MISSING "$sub (in no layer, for $dest)"; return 0
  fi
  [[ $MODE == uninstall ]] || record link "$dest"
  place_link "$src" "$dest"
}

# link_each <dir> <dest dir>
# Symlink every item (file or directory, dotfiles skipped) of <dir> from every
# layer into dest dir under the same name. Same name in two layers: the later
# layer's item wins, with a WARN. Other items in dest dir are left alone.
link_each() {
  local sub="$1" dest="$2" l item name prev rname rl keep i j l2
  claim "$dest" "link_each $sub" || return 0
  : > "$TMPD/items"
  : > "$TMPD/removes"
  for l in "${LAYERS[@]}"; do
    [[ -d $l/$sub ]] || continue
    for item in "$l/$sub"/* "$l/$sub"/.*; do
      [[ -e $item || -L $item ]] || continue
      name="${item##*/}"
      case $name in .|..) continue ;; esac
      # .remove-<x> lists item names (one per line) that this layer removes
      # from lower layers.
      case $name in
        .remove-*)
          while IFS= read -r rname; do
            case $rname in ''|\#*) continue ;; esac
            printf '%s\t%s\n' "$rname" "$l" >> "$TMPD/removes"
          done < "$item"
          continue
          ;;
      esac
      prev="$(awk -F'\t' -v n="$name" '$1 == n { p = $3 } END { print p }' "$TMPD/items")"
      [[ -n $prev ]] && warn "$dest/$name: $(layer_name "$l") overrides $(layer_name "$prev")"
      printf '%s\t%s\t%s\n' "$name" "$item" "$l" >> "$TMPD/items"
    done
  done
  ensure_dir "$dest"
  # Last entry per name wins; keep first-seen order.
  awk -F'\t' '!($1 in src) { order[++n] = $1 } { src[$1] = $2; lyr[$1] = $3 }
    END { for (i = 1; i <= n; i++) print order[i] "\t" src[order[i]] "\t" lyr[order[i]] }' \
    "$TMPD/items" > "$TMPD/winners"
  while IFS=$'\t' read -r name item l <&3; do
    # A remove entry from a layer above the item's layer drops the item.
    keep=1; i=-1
    for l2 in "${LAYERS[@]}"; do
      [[ $l2 == "$l" ]] && break
      i=$((i + 1))
    done
    while IFS=$'\t' read -r rname rl; do
      [[ $rname == "$name" ]] || continue
      j=-1
      for l2 in "${LAYERS[@]}"; do
        [[ $l2 == "$rl" ]] && break
        j=$((j + 1))
      done
      if (( j > i )); then
        keep=0
        say removed "$dest/$name (removed by $(layer_name "$rl"))"
      fi
    done < "$TMPD/removes"
    (( keep )) || continue
    [[ $MODE == uninstall ]] || record link "$dest/$name"
    place_link "$item" "$dest/$name"
  done 3< "$TMPD/winners"
}

# Marker lines of a managed block, per comment style.
block_markers() {
  case $1 in
    hash) B='# >>> dotfiles >>>';         E='# <<< dotfiles <<<' ;;
    lua)  B='-- >>> dotfiles >>>';        E='-- <<< dotfiles <<<' ;;
    html) B='<!-- >>> dotfiles >>> -->';  E='<!-- <<< dotfiles <<< -->' ;;
    *)    echo "unknown block style '$1'" >&2; return 1 ;;
  esac
}

# block_edit <file> <style> <top|bottom> <block body file>: print file with its
# managed block replaced by the body (in place), or inserted at top/bottom if
# it has none. An empty body removes the block. Exits 3 on an unterminated block.
block_edit() {
  block_markers "$2" || return 1
  awk -v b="$B" -v e="$E" -v pos="$3" -v body="$4" -v empty="$([[ -s $4 ]] && echo 0 || echo 1)" '
    function emit(  l) {
      if (empty) return
      print b
      while ((getline l < body) > 0) print l
      close(body)
      print e
    }
    { L[NR] = $0 }
    END {
      s = 0; t = 0
      for (i = 1; i <= NR; i++) if (L[i] == b) { s = i; break }
      if (s) {
        for (j = s + 1; j <= NR; j++) if (L[j] == e) { t = j; break }
        if (!t) exit 3
        for (i = 1; i < s; i++) print L[i]
        emit()
        for (i = t + 1; i <= NR; i++) print L[i]
      } else if (pos == "top") {
        emit()
        for (i = 1; i <= NR; i++) print L[i]
      } else {
        for (i = 1; i <= NR; i++) print L[i]
        emit()
      }
    }' "$1"
}

# block <dest> <top|bottom> <hash|lua|html> <render command...>
# Keep a managed block, holding the render command's output, in a file the
# host owns. Everything outside the markers is the host's: lines after a
# top block (or before a bottom one, for first-match formats like ssh)
# override the layers. A missing file is created with just the block.
block() {
  local dest="$1" pos="$2" style="$3" current="" t
  shift 3
  claim "$dest" "block $pos $style $*" || return 0
  free_parents "$dest"
  [[ $GONE == 1 ]] || current="$(abs_target "$dest")"

  if [[ $MODE == uninstall ]]; then
    unmanage "block:$style" "$dest"; return 0
  fi
  record "block:$style" "$dest"

  # Starting content: none if dest is an old link into a layer (its content
  # was the repo's), else the existing file (read through any other link).
  : > "$TMPD/base"
  if [[ $GONE != 1 && -e $dest ]] && ! in_layer "$current"; then
    cat "$dest" > "$TMPD/base"
  fi
  "$@" > "$TMPD/body" || { problem BAD "$dest (rendering the block failed)"; return 0; }
  if ! block_edit "$TMPD/base" "$style" "$pos" "$TMPD/body" > "$TMPD/new"; then
    problem BAD "$dest (block start marker without an end marker)"; return 0
  fi

  if [[ -z $current && $GONE != 1 ]] && cmp -s "$TMPD/new" "$dest" 2>/dev/null; then
    [[ $MODE == status ]] && say ok "$dest"
    return 0
  fi
  if [[ $MODE == status ]]; then
    if [[ $GONE == 1 ]]; then say absent "$dest"
    elif [[ -n $current ]] && in_layer "$current"; then say LEGACY "$dest -> $current"
    elif [[ -n $current ]]; then say OTHER "$dest -> $current (becomes a real file)"
    elif grep -qxF -e "$B" "$dest" 2>/dev/null; then say DIFF "$dest (block is stale)"
    else say absent "$dest (no block yet)"
    fi
    return 0
  fi

  if [[ -n $current && $GONE != 1 ]]; then
    if in_layer "$current"; then
      say unlink "$dest (old link -> $current)"
    else
      say backup "$dest -> $dest.backup.$STAMP (link to $current, copied into a real file)"
      run mv "$dest" "$dest.backup.$STAMP"
    fi
    run rm -f "$dest"
  elif [[ $GONE != 1 && -s $dest ]] && ! grep -qxF -e "$B" "$dest"; then
    say backup "$dest -> $dest.backup.$STAMP (before adding the block)"
    run cp -p "$dest" "$dest.backup.$STAMP"
  fi
  put_file "$dest" "$TMPD/new" block
}

# generate <dest> <render command...>
# Write the render command's output, under a "generated" header line, as the
# whole of dest. For files without includes whose format uses # comments.
# Host overrides belong in the host layer, not in dest.
generate() {
  local dest="$1" current=""
  shift
  claim "$dest" "generate $*" || return 0
  free_parents "$dest"
  [[ $GONE == 1 ]] || current="$(abs_target "$dest")"

  if [[ $MODE == uninstall ]]; then
    unmanage gen "$dest"; return 0
  fi
  record gen "$dest"

  { echo "# $GEN_MARK"; "$@"; } > "$TMPD/new" ||
    { problem BAD "$dest (rendering failed)"; return 0; }

  if [[ $GONE != 1 && -z $current ]] && cmp -s "$TMPD/new" "$dest" 2>/dev/null; then
    [[ $MODE == status ]] && say ok "$dest"
    return 0
  fi
  if [[ $MODE == status ]]; then
    if [[ $GONE == 1 || ! -e $dest && -z $current ]]; then say absent "$dest"
    elif [[ -n $current ]] && in_layer "$current"; then say LEGACY "$dest -> $current"
    elif [[ -n $current ]]; then say OTHER "$dest -> $current"
    elif is_generated "$dest"; then say DIFF "$dest"
    else say FILE "$dest (not generated)"
    fi
    return 0
  fi

  if [[ $GONE != 1 ]]; then
    if [[ -n $current ]] && in_layer "$current"; then
      say unlink "$dest (old link -> $current)"; run rm "$dest"
    elif [[ -n $current ]] || { [[ -e $dest ]] && ! is_generated "$dest"; }; then
      say backup "$dest -> $dest.backup.$STAMP"
      run mv "$dest" "$dest.backup.$STAMP"
    fi
  fi
  put_file "$dest" "$TMPD/new" generate
}

is_generated() { [[ -f $1 && ! -L $1 ]] && [[ "$(head -n 1 "$1")" == *"$GEN_MARK"* ]]; }

# Print a JSON file with // and /* */ comments and trailing commas removed
# (VS Code style JSONC), so jq can read it.
strip_jsonc() {
  awk 'BEGIN { RS = "\001" }
  {
    s = $0; n = length(s); out = ""; i = 1; instr = 0; pend = 0; ws = ""
    while (i <= n) {
      c = substr(s, i, 1)
      if (instr) {
        out = out c
        if (c == "\\") { out = out substr(s, i + 1, 1); i += 2; continue }
        if (c == "\"") instr = 0
        i++; continue
      }
      two = substr(s, i, 2)
      if (two == "//") { while (i <= n && substr(s, i, 1) != "\n") i++; continue }
      if (two == "/*") {
        j = index(substr(s, i + 2), "*/"); i = j ? i + j + 3 : n + 1; continue
      }
      if (c == ",") { if (pend) out = out "," ws; pend = 1; ws = ""; i++; continue }
      if (pend) {
        if (c == " " || c == "\t" || c == "\r" || c == "\n") { ws = ws c; i++; continue }
        if (c != "}" && c != "]") out = out ","
        out = out ws; pend = 0; ws = ""
      }
      if (c == "\"") instr = 1
      out = out c; i++
    }
    if (pend) out = out "," ws
    printf "%s", out
  }' "$1"
}

# Where json remembers what it last applied to a destination.
json_state() {
  printf '%s/json/%s.json' "$BUILD" "$(printf '%s' "$1" | sed 's|^/||; s|[/ ]|%|g')"
}

# jq program: given the live file (.), the merged layers ($m) and what was
# applied last time ($p), drop what the layers no longer set (where the live
# value is still the one setup wrote), then merge $m over the result. Objects
# merge recursively (arrays inside are replaced); a top-level array (e.g.
# VS Code keybindings) gets the layers' entries appended if missing. A null
# in $m deletes the key (from the live file too), so a higher layer can undo
# a lower layer's key.
JSON_APPLY='
def has_el($a; $x): any($a[]; . == $x);
def get($q): try getpath($q) catch null;
def has_path($q):
  try (getpath($q[:-1]) | if type == "object" then has($q[-1]) else false end) catch false;
(. // (if ($m | type) == "array" then [] else {} end)) as $live
| if ($m | type) == "array" then
    ($p // []) as $p
    | $live
    | map(select((has_el($p; .) and (has_el($m; .) | not)) | not))
    | reduce $m[] as $x (.; if has_el(.; $x) then . else . + [$x] end)
  else
    ($p // {}) as $p
    | reduce ($p | [paths(type != "object")] | map(select(all(.[]; type == "string"))))[] as $q
        ($live;
         if ($m | has_path($q) | not) and get($q) == ($p | get($q)) then delpaths([$q]) else . end)
    | ($m | [paths(type == "null")] | map(select(all(.[]; type == "string")))) as $del
    | reduce $del[] as $q (.; delpaths([$q]))
    | . * (reduce $del[] as $q ($m; delpaths([$q])))
  end'

# json <path> <dest> [jq filter]
# For JSON configs the app also writes itself (settings files). Deep-merges
# <path> from every layer (later wins; JSONC comments allowed) over the live
# file, which keeps every key the layers don't set. The filter runs on the
# result. Keys a layer stops setting are removed again. Needs jq.
json() {
  local sub="$1" dest="$2" filter="${3:-.}" l n=0 current="" state live
  claim "$dest" "json $sub $filter" || return 0
  if [[ $MODE == uninstall ]]; then
    unmanage json "$dest"; return 0
  fi
  record json "$dest"
  if ! command -v jq >/dev/null 2>&1; then
    problem NO-JQ "$dest (jq is needed to merge $sub)"; return 0
  fi

  for l in "${LAYERS[@]}"; do
    [[ -f $l/$sub ]] || continue
    n=$((n + 1))
    if ! strip_jsonc "$l/$sub" | jq . > "$TMPD/layer.$n.json"; then
      problem BAD "$l/$sub (not valid JSON)"; return 0
    fi
  done
  if (( n == 0 )); then
    problem MISSING "$sub (in no layer, for $dest)"; return 0
  fi
  local files=() i
  for ((i = 1; i <= n; i++)); do files+=("$TMPD/layer.$i.json"); done
  if ! jq -n 'reduce inputs as $x (null;
        if . == null then $x elif type == "array" then . + $x else . * $x end)' \
        "${files[@]}" > "$TMPD/merged.json"; then
    problem BAD "$sub (layers don't merge: mixed types?)"; return 0
  fi

  free_parents "$dest"
  [[ $GONE == 1 ]] || current="$(abs_target "$dest")"
  live="$TMPD/live.json"
  if [[ $GONE != 1 && -e $dest ]] && ! in_layer "$current"; then
    strip_jsonc "$dest" > "$live"
    if ! jq . "$live" >/dev/null 2>&1; then
      problem BAD "$dest (not valid JSON)"; return 0
    fi
  else
    : > "$live"
  fi
  state="$(json_state "$dest")"
  [[ -f $state ]] || state=/dev/null
  if ! jq -s --slurpfile m "$TMPD/merged.json" --slurpfile p "$state" \
        "\$m[0] as \$m | (\$p[0] // null) as \$p | (.[0] // null) | $JSON_APPLY | $filter" \
        "$live" > "$TMPD/new"; then
    problem BAD "$dest (merge failed)"; return 0
  fi

  if [[ $GONE != 1 && -z $current && -e $dest ]] && cmp -s "$TMPD/new" "$dest"; then
    [[ $MODE == status ]] && say ok "$dest (merged)"
    [[ $MODE == install ]] && save_json_state "$dest"
    return 0
  fi
  if [[ $MODE == status ]]; then
    if [[ $GONE == 1 || ! -e $dest && -z $current ]]; then say absent "$dest"
    elif [[ -n $current ]] && in_layer "$current"; then say LEGACY "$dest -> $current"
    elif [[ -n $current ]]; then say OTHER "$dest -> $current"
    else say DIFF "$dest (differs from the layers)"
    fi
    return 0
  fi

  if [[ -n $current && $GONE != 1 ]]; then
    if in_layer "$current"; then say unlink "$dest (old link -> $current)"
    else say backup "$dest -> $dest.backup.$STAMP"; run mv "$dest" "$dest.backup.$STAMP"
    fi
    run rm -f "$dest"
  elif [[ -e $dest && $GONE != 1 ]]; then
    say backup "$dest -> $dest.backup.$STAMP"
    run cp -p "$dest" "$dest.backup.$STAMP"
  fi
  put_file "$dest" "$TMPD/new" merge
  [[ $MODE == install ]] && save_json_state "$dest"
  return 0
}

save_json_state() {
  local state
  state="$(json_state "$1")"
  mkdir -p "$(dirname "$state")"
  cp "$TMPD/merged.json" "$state"
}

# step <name> <check function> <apply function>
# For setup that isn't a file: fetching submodules, installing fonts, terminal
# settings. The check returns 0 when nothing needs doing (its output is
# hidden); the apply function does the work. Uninstall leaves steps alone.
step() {
  local name="$1" check="$2" apply="$3"
  claim "step: $name" "step $check $apply" || return 0
  case $MODE in
    status)
      if "$check" >/dev/null 2>&1; then say ok "$name"; else say todo "$name"; fi
      ;;
    uninstall) ;;
    install|dry-run)
      "$check" >/dev/null 2>&1 && return 0
      say run "$name"
      if [[ $MODE == install ]] && ! "$apply"; then
        problem FAILED "$name"; return 0
      fi
      changes=$((changes + 1))
      ;;
  esac
}

# shadow_check <dir>: warn when two layers have the same file under <dir>
# (e.g. nvim/lua, where the later layer's module hides the earlier one's).
shadow_check() {
  local sub="$1" l
  for l in "${LAYERS[@]}"; do
    [[ -d $l/$sub ]] || continue
    (cd "$l/$sub" && find . -type f) | sed "s|^\./||" | awk -v l="$l" '{ print $0 "\t" l }'
  done | awk -F'\t' '$1 in seen { print $1 "\t" seen[$1] "\t" $2 } { seen[$1] = $2 }' \
    > "$TMPD/shadows"
  local rel lo hi
  while IFS=$'\t' read -r rel lo hi <&3; do
    warn "$sub/$rel: $(layer_name "$hi") shadows $(layer_name "$lo")"
  done 3< "$TMPD/shadows"
}

# -------------------------------------------------------------- renderers ---
# Commands that print content for `block` and `generate`. Layers can define
# their own; iterate "${LAYERS[@]}" (lowest precedence first).

# render_concat <path> <label format> [separator line]
# Every layer's <path>, in order, each introduced by printf <label format> <file>.
render_concat() {
  local sub="$1" fmt="$2" sep="${3:-}" l first=1
  for l in "${LAYERS[@]}"; do
    [[ -f $l/$sub ]] || continue
    if [[ $first == 0 ]]; then
      if [[ -n $sep ]]; then echo "$sep"; else echo; fi
    fi
    first=0
    # shellcheck disable=SC2059
    printf "$fmt\n" "$l/$sub"
    cat "$l/$sub"
    # Keep the next label on its own line even without a final newline.
    [[ -z $(tail -c 1 "$l/$sub") ]] || echo
  done
}

# render_each <format> <path> [reverse]
# One line per layer: printf <format> <layer>/<path>, whether or not the file
# exists yet (for includes that ignore missing files, like tmux's
# `source-file -q` and ssh's Include). `reverse` puts the highest layer first,
# for formats where the first value wins.
render_each() {
  local fmt="$1" sub="$2" i
  if [[ ${3:-} == reverse ]]; then
    for ((i = ${#LAYERS[@]} - 1; i >= 0; i--)); do
      # shellcheck disable=SC2059
      printf "$fmt\n" "${LAYERS[i]}/$sub"
    done
  else
    for ((i = 0; i < ${#LAYERS[@]}; i++)); do
      # shellcheck disable=SC2059
      printf "$fmt\n" "${LAYERS[i]}/$sub"
    done
  fi
}

# render_lines <line>...: the given lines, verbatim.
render_lines() { printf '%s\n' "$@"; }

# ------------------------------------------------------------- bookkeeping ---

# unmanage <kind> <dest>: undo one managed destination.
unmanage() {
  local kind="$1" dest="$2" state t
  case $kind in
    link)
      [[ -L $dest ]] || return 0
      say remove "$dest -> $(link_target "$dest")"
      run rm "$dest"; changes=$((changes + 1))
      ;;
    gen)
      is_generated "$dest" || return 0
      say remove "$dest"
      run rm "$dest"; changes=$((changes + 1))
      ;;
    block:*)
      [[ -f $dest && ! -L $dest ]] || {
        # An old link into a layer counts as ours too.
        t="$(abs_target "$dest")"
        if [[ -n $t ]] && in_layer "$t"; then
          say remove "$dest -> $t"; run rm "$dest"; changes=$((changes + 1))
        fi
        return 0
      }
      : > "$TMPD/empty"
      block_edit "$dest" "${kind#block:}" top "$TMPD/empty" > "$TMPD/unblocked" || return 0
      cmp -s "$TMPD/unblocked" "$dest" && return 0
      if [[ -z $(tr -d ' \t\n' < "$TMPD/unblocked") ]]; then
        say remove "$dest (only held the block)"
        run rm "$dest"
      else
        say unblock "$dest"
        [[ $MODE == dry-run ]] || cat "$TMPD/unblocked" > "$dest"
      fi
      changes=$((changes + 1))
      ;;
    json)
      state="$(json_state "$dest")"
      if [[ -L $dest ]]; then
        t="$(abs_target "$dest")"
        if in_layer "$t"; then
          say remove "$dest -> $t"; run rm "$dest"; changes=$((changes + 1))
        fi
        return 0
      fi
      [[ -f $state && -f $dest ]] || return 0
      command -v jq >/dev/null 2>&1 || { problem NO-JQ "$dest (jq is needed to unmerge)"; return 0; }
      strip_jsonc "$dest" > "$TMPD/live.json"
      jq -n --slurpfile x "$state" '$x[0] | if type == "array" then [] else {} end' > "$TMPD/m.json"
      if ! jq -s --slurpfile m "$TMPD/m.json" --slurpfile p "$state" \
            "\$m[0] as \$m | (\$p[0] // null) as \$p | (.[0] // null) | $JSON_APPLY" \
            "$TMPD/live.json" > "$TMPD/new"; then
        problem BAD "$dest (unmerge failed)"; return 0
      fi
      if jq -e 'length == 0' "$TMPD/new" >/dev/null 2>&1; then
        say remove "$dest (nothing left but what setup merged in)"
        run rm "$dest"
        changes=$((changes + 1))
      elif ! cmp -s "$TMPD/new" "$dest"; then
        say unmerge "$dest"
        [[ $MODE == dry-run ]] || cat "$TMPD/new" > "$dest"
        changes=$((changes + 1))
      fi
      run rm "$state"
      ;;
  esac
}

# Undo what the previous run managed that this one didn't declare: a layer
# dropped from the stack, a file removed from a layer, a target removed.
prune() {
  local kind dest
  [[ -f $RECORD ]] || return 0
  while IFS=$'\t' read -r kind dest <&3; do
    [[ -n $dest ]] || continue
    grep -qxF "$kind"$'\t'"$dest" "$TMPD/record" && continue
    if [[ $MODE == status ]]; then
      say stale "$dest (managed by an earlier run; removed on setup)"
    else
      unmanage "$kind" "$dest"
    fi
  done 3< "$RECORD"
}

# ------------------------------------------------------------------- main ---

build_main() {
  local l layer_args=() abs
  while (( $# )); do
    case $1 in
      -n|--dry-run)   MODE=dry-run ;;
      -s|--status)    MODE=status ;;
      -u|--uninstall) MODE=uninstall ;;
      -h|--help)      build_usage; exit 0 ;;
      --layer)
        [[ $# -ge 2 ]] || { build_usage >&2; exit 2; }
        layer_args+=("$2"); shift ;;
      --skip)
        [[ $# -ge 2 ]] || { build_usage >&2; exit 2; }
        SKIPS+=("$2"); shift ;;
      *) build_usage >&2; exit 2 ;;
    esac
    shift
  done

  LAYERS=("$DOTFILES")
  for l in ${layer_args[@]+"${layer_args[@]}"}; do
    abs="$(cd "$l" 2>/dev/null && pwd -P)" || { echo "error: layer '$l' is not a directory" >&2; exit 1; }
    if in_layer "$abs"; then
      echo "error: layer '$abs' is already in the stack" >&2; exit 1
    fi
    LAYERS+=("$abs")
  done
  if [[ -d $HOST_LAYER ]]; then
    abs="$(cd "$HOST_LAYER" && pwd -P)"
    HOST_LAYER="$abs"
    in_layer "$abs" || LAYERS+=("$abs")
  fi

  TMPD="$(mktemp -d "${TMPDIR:-/tmp}/dotfiles.XXXXXX")"
  trap 'rm -rf "$TMPD"' EXIT
  : > "$TMPD/record"
  : > "$TMPD/claims"
  : > "$TMPD/legacy"

  echo "dotfiles: $(basename "$0") $MODE"
  for l in "${LAYERS[@]}"; do echo "  layer    $(layer_name "$l")  $l"; done

  for l in "${LAYERS[@]}"; do
    [[ -f $l/layer.sh ]] || continue
    echo "$(layer_name "$l")/layer.sh"
    LAYER="$l"
    # shellcheck disable=SC1090,SC1091
    . "$l/layer.sh"
  done
  LAYER=""

  echo "cleanup"
  prune
  case $MODE in
    install)
      mkdir -p "$BUILD"
      sort -u "$TMPD/record" > "$RECORD"
      ;;
    uninstall)
      rm -f "$RECORD"
      rmdir "$BUILD/json" "$BUILD" 2>/dev/null || true
      ;;
  esac

  case $MODE in
    install)   echo "$changes change(s) made." ;;
    dry-run)   echo "$changes change(s) would be made." ;;
    uninstall) echo "$changes item(s) removed." ;;
  esac
  (( warnings == 0 )) || echo "$warnings warning(s): a later layer overrides an earlier one."
  (( problems == 0 )) || { echo "$problems problem(s)." >&2; exit 1; }
}
